[project]
name = "fxb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "夏天", email = "xiat@ruc.edu.cn" }
]
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "httpx>=0.28.1",
    "requests>=2.32.5",
]

[project.scripts]
fxb = "fxb:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
